dist: trusty
before_install: 
  -"export DISPLAY=:99.0"
  -"sh -e /etc/init.d/xvfb start"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "12.18.3"